### ISSUE TITLE
[BUG] Kernel build fails due to bug retrieving public_sources_tbz2

### ISSUE THREAD

**Issue by maburlik** [jetsonhacks/jetson-linux-build#1]
**Describe the issue**

./getKernelSources.sh 

nvidia@tegra-ubuntu:~/jetson-linux-build$ **./getKernelSources.sh**
NVIDIA Jetson TX2
Jetpack UNKNOWN [L4T N.N.N]
Kernel Release: 4.4
Placing kernel source into /usr/src/
[sudo] password for nvidia:
./scripts/getKernelSources.sh: line 74: [: =: unary operator expected
'universe' distribution component enabled for all sources.
Hit:1 http://ports.ubuntu.com/ubuntu-ports xenial InRelease
Get:2 http://ports.ubuntu.com/ubuntu-ports xenial-updates InRelease [109 kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports xenial-security InRelease [109 kB]
Get:4 http://ports.ubuntu.com/ubuntu-ports xenial/universe Sources [7,728 kB]
Get:5 http://ports.ubuntu.com/ubuntu-ports xenial/universe arm64 Packages [7,275 kB]
Get:6 http://ports.ubuntu.com/ubuntu-ports xenial/universe Translation-en [4,354 kB]
Get:7 http://ports.ubuntu.com/ubuntu-ports xenial/universe arm64 DEP-11 Metadata [3,362 kB]
Get:8 http://ports.ubuntu.com/ubuntu-ports xenial/universe DEP-11 64x64 Icons [7,448 kB]
Get:9 http://ports.ubuntu.com/ubuntu-ports xenial-updates/universe Sources [444 kB]
Get:10 http://ports.ubuntu.com/ubuntu-ports xenial-updates/main arm64 DEP-11 Metadata [321 kB]
Get:11 http://ports.ubuntu.com/ubuntu-ports xenial-updates/universe arm64 Packages [1,159 kB]
Get:12 http://ports.ubuntu.com/ubuntu-ports xenial-updates/universe Translation-en [358 kB]
Get:13 http://ports.ubuntu.com/ubuntu-ports xenial-updates/universe arm64 DEP-11 Metadata [279 kB]
Get:14 http://ports.ubuntu.com/ubuntu-ports xenial-updates/universe DEP-11 64x64 Icons [437 kB]
Get:15 http://ports.ubuntu.com/ubuntu-ports xenial-security/universe Sources [211 kB]
Get:16 http://ports.ubuntu.com/ubuntu-ports xenial-security/main arm64 DEP-11 Metadata [88.1 kB]
Get:17 http://ports.ubuntu.com/ubuntu-ports xenial-security/universe arm64 Packages [754 kB]
Get:18 http://ports.ubuntu.com/ubuntu-ports xenial-security/universe Translation-en [225 kB]
Get:19 http://ports.ubuntu.com/ubuntu-ports xenial-security/universe arm64 DEP-11 Metadata [125 kB]
Get:20 http://ports.ubuntu.com/ubuntu-ports xenial-security/universe DEP-11 64x64 Icons [206 kB]
Fetched 35.0 MB in 7s (4,860 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
pkg-config is already the newest version (0.29.1-0ubuntu1).
pkg-config set to manually installed.
The following package was automatically installed and is no longer required:
  libqmi-glib1
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following package was automatically installed and is no longer required:
  libqmi-glib1
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  libtinfo-dev
Suggested packages:
  ncurses-doc
The following NEW packages will be installed:
  libncurses5-dev libtinfo-dev
0 upgraded, 2 newly installed, 0 to remove and 5 not upgraded.
Need to get 235 kB of archives.
After this operation, 1,359 kB of additional disk space will be used.
Get:1 http://ports.ubuntu.com/ubuntu-ports xenial/main arm64 libtinfo-dev arm64 6.0+20160213-1ubuntu1 [71.5 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports xenial/main arm64 libncurses5-dev arm64 6.0+20160213-1ubuntu1 [163 kB]
Fetched 235 kB in 0s (374 kB/s)
Selecting previously unselected package libtinfo-dev:arm64.
(Reading database ... 149519 files and directories currently installed.)
Preparing to unpack .../libtinfo-dev_6.0+20160213-1ubuntu1_arm64.deb ...
Unpacking libtinfo-dev:arm64 (6.0+20160213-1ubuntu1) ...
Selecting previously unselected package libncurses5-dev:arm64.
Preparing to unpack .../libncurses5-dev_6.0+20160213-1ubuntu1_arm64.deb ...
Unpacking libncurses5-dev:arm64 (6.0+20160213-1ubuntu1) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up libtinfo-dev:arm64 (6.0+20160213-1ubuntu1) ...
Setting up libncurses5-dev:arm64 (6.0+20160213-1ubuntu1) ...
/usr/src/linux-headers-4.4.38-tegra-ubuntu16.04_aarch64/kernel-4.4/Module.symvers
/usr/src
http://: Invalid host name.
tar: public_sources.tbz2: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
kernel/nvhost/
kernel/nvhost/include/
....

Build error compiling the kernel using
nvidia@tegra-ubuntu:~/jetson-linux-build$ **./makeKernel.sh**

drivers/devfreq/governor_pod_scaling.c:54:22: fatal error: governor.h: No such file or directory
compilation terminated.
scripts/Makefile.build:261: recipe for target 'drivers/devfreq/governor_pod_scaling.o' failed
make[2]: *** [drivers/devfreq/governor_pod_scaling.o] Error 1
scripts/Makefile.build:406: recipe for target 'drivers/devfreq' failed
make[1]: *** [drivers/devfreq] Error 2
make[1]: *** Waiting for unfinished jobs....
...
drivers/devfreq/governor_pod_scaling.c:54:22: fatal error: governor.h: No such file or directory
compilation terminated.
scripts/Makefile.build:261: recipe for target 'drivers/devfreq/governor_pod_scaling.o' failed
make[2]: *** [drivers/devfreq/governor_pod_scaling.o] Error 1
scripts/Makefile.build:406: recipe for target 'drivers/devfreq' failed
make[1]: *** [drivers/devfreq] Error 2
Makefile:973: recipe for target 'drivers' failed
make: *** [drivers] Error 2
Make did not successfully build
Please fix issues and retry build

**Which version of Ubuntu on the Host machine**
Ubuntu version: 
root@tegra-ubuntu:/# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.7 LTS
Release:        16.04
Codename:       xenial

root@tegra-ubuntu:/# uname -r
4.4.38-tegra

**What version of L4T/JetPack**
L4T/JetPack version: N/A

**Which Jetson**
Jetson: TX2

**To Reproduce**
For example, what command line did you run?
./getKernelSources.sh
./makeKernel.sh

**Expected behavior**
Expected public sources to download & kernel build to succeed.

**Additional context**
N/A

**Comment by maburlik** [comment]
This is a fresh out of box TX2 and it could be I am missing the L4T components since some of the tools and components in your documentation are missing from the machine. It's possible the issue is just in early validation steps, and further prerequisites are required before running the scripts.

As a result of missing components, jetson_variables may not be able to identify the variables for package mapping.

I've made a few local changes:

diff --git a/scripts/getKernelSources.sh b/scripts/getKernelSources.sh
index 3a6ce78..998b988 100755
--- a/scripts/getKernelSources.sh
+++ b/scripts/getKernelSources.sh
@@ -71,7 +71,7 @@ case ${BOARD_ID} in
     exit 1
 esac

-if [ $SOURCE_URL = "" ] ; then
+if [ "$SOURCE_URL" = "" ] ; then
   echo "Unable to find source files on developer.nvidia.com"
   echo "L4T $JETSON_L4T"
   exit 1
@@ -105,11 +105,25 @@ echo $MODULE_SYMVERS_URL
 cd "$SOURCE_TARGET"
 echo "$PWD"
 # L4T Driver Package (BSP) Sources
+echo "Downloading from $SOURCE_URL"
 wget -N "$SOURCE_URL"

+if [ ! -f "public_sources.tbz2" ]; then
+  echo "public_sources.tbz2 did not download."
+  exit 1
+fi
+
 # l4t-sources is a tbz2 file
 tar -xvf public_sources.tbz2  Linux_for_Tegra/source/public/kernel_src.tbz2 --strip-components=3
+if [ !$? ]; then
+  echo "extracting public_sources.tbz2 failed."
+  exit 1
+fi
 tar -xvf kernel_src.tbz2
+if [ !$? ]; then
+  echo "extracting kernel_src.tbz2 failed."
+  exit 1
+fi

**Comment by jetsonhacks** [comment]
@maburlik Typically people will flash a Jetson with the latest version of JetPack after receiving the device: https://developer.nvidia.com/embedded/jetpack The current release is JetPack 4.6.

The version that you are using is the original golden master placeholder that they flash at the factory. The Jetson TX2 has been around for a few years, there have been many changes since then. The current kernel revision is 4.9, the one you have is 4.4. This repository attempts to have a common build across the Jetson Devkits starting with L4T 32.4.2, JetPack 4.4 Developer preview. 

Earlier versions of this repo, such as for the one you are using, build the kernel for earlier releases. See: https://github.com/jetsonhacks/buildJetsonTX2Kernel

Thank you for the code, it is always helpful when errors are encountered to give an explanation of the problem! Plus, it looks like I bungled the empty string comparison for the SOURCE_URL. Stupid bash string expansion!

**Comment by aiLab-wu** [comment]
Does this code currently support Orin? My platform is L4T35.1.0 and Jetpack is 5.0.2.
