### ISSUE TITLE
Couldn't fixed the same error on Orin

### ISSUE THREAD

**Issue by aiLab-wu** [jetsonhacks/jetson-linux-build#4]
When can it be supported on Orin?

**Comment by jetsonhacks** [comment]
Give version v1.1 a try.

**Comment by aiLab-wu** [comment]
> Give version v1.1 a try.

Thank you! 

After my Orin executed the "./getKernelSources.sh" command to download the kernel source compressed package, the following error occurred:
“tar: public_sources.tbz2: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
tar: kernel_src.tbz2: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
rm: cannot remove 'kernel_src.tbz2': No such file or directory
./scripts/getKernelSources.sh: line 120: cd: kernel/kernel-5.10: No such file or directory
/usr/src
bash: scripts/config: No such file or directory”
How can it be repaired?

**Comment by jetsonhacks** [comment]
Selected the wrong file. Try it again and see if it is fixed.

**Comment by aiLab-wu** [comment]
> Selected the wrong file. Try it again and see if it is fixed.

Thank you! It finally worked.
